slurmstepd: info: Setting TMPDIR to /scratch/10942690. Previous errors about TMPDIR can be discarded
Slurm job started at 12/03/2025_06:47:21 PM

In situ 2,
Initing Ray (1 head node + 2 worker nodes + 4 simulation nodes) on nodes: 
	ilk-145 ilk-146 ilk-147 ilk-148 ilk-149 ilk-151 ilk-153
Head node: 172.30.204.1:6379


RAY_DEPLOY_TIME:     23.26555
2025-03-12 18:47:48,612	INFO packaging.py:520 -- Creating a file package for local directory '/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E6/DASK_ON_REISA_ONE_ACTOR/derivative/P128-SN4-LS134-GS17179-I10-AN2-D2025-03-12_10-04-42'.
2025-03-12 18:47:48,641	INFO packaging.py:347 -- Pushing file package 'gcs://_ray_pkg_c0a333781ecf0501.zip' (0.48MiB) to Ray cluster...
2025-03-12 18:47:48,647	INFO packaging.py:360 -- Successfully pushed file package 'gcs://_ray_pkg_c0a333781ecf0501.zip'.
RAY_INIT_TIME:       4.66425
Iter [0]
Iter [1]
Iter [2]
Iter [3]
Iter [4]
Iter [5]
Iter [6]
Iter [7]
Iter [8]
Iter [9]
GLOBAL_PUT_TIME:     7.37417197227478 (avg:0.73742)
ACTOR_CONCURRENCY:   8
SIMULATION_TIME:     299.781563204000008 (avg: 29.978156320400000)
SIM_WTHOUT_PDI:      46.180319554999969 (avg: 4.618031955499997)
PDI_DELAY:           253.601243649000025 (avg: 25.360124364900003)

GLOBAL_SIZE_(GiB):   16777216
LOCAL_SIZE_(MiB):    128
ITERATIONS:          10

MPI_PER_NODE:        32
MPI_PARALLELISM:     128

WORKER_NODES:        2
CPUS_PER_WORKER:     64
WORKER_PARALLELISM:  128


SLURM_JOB_ID:        10942690
WARNING: 12 PYTHON worker processes have been started on node: 4c1d8f5835956b87ab573a86e8ea7fa5bbe0347dc505a428caa27694 with address: 172.30.204.4. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:01:46,085 E 3645889 3646047] (raylet) file_system_monitor.cc:111: /scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500 is over 99.9% full, available space: 670806016; capacity: 837278007296. Object creation will fail if spilling is required.
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:01:56,088 E 3645889 3646047] (raylet) file_system_monitor.cc:111: /scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500 is over 99.9% full, available space: 0; capacity: 837278007296. Object creation will fail if spilling is required.
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m terminate called after throwing an instance of 'spdlog::spdlog_ex'
[2m[33m(raylet, ip=10.120.204.4)[0m   what():  Failed opening file /scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/logs/python-core-worker-2d5553f40bf26a190fca938761290782990efcb12f258dc6f4ddd466_3691959.log for writing: No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m Fatal Python error: Aborted
[2m[33m(raylet, ip=10.120.204.4)[0m 
[2m[33m(raylet, ip=10.120.204.4)[0m Stack (most recent call first):
[2m[33m(raylet, ip=10.120.204.4)[0m   File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/worker.py", line 2189 in connect
[2m[33m(raylet, ip=10.120.204.4)[0m   File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/workers/default_worker.py", line 234 in <module>
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:02:06,115 E 3645889 3646047] (raylet) file_system_monitor.cc:111: /scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500 is over 99.9% full, available space: 0; capacity: 837278007296. Object creation will fail if spilling is required.
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m terminate called after throwing an instance of 'spdlog::spdlog_ex'
[2m[33m(raylet, ip=10.120.204.4)[0m   what():  Failed opening file /scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/logs/python-core-worker-333ed943a8bac79ff935bb63e97f699c6a0cb2c99f10a5358d2a56b0_3692595.log for writing: No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m Fatal Python error: Aborted
[2m[33m(raylet, ip=10.120.204.4)[0m 
[2m[33m(raylet, ip=10.120.204.4)[0m Stack (most recent call first):
[2m[33m(raylet, ip=10.120.204.4)[0m   File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/worker.py", line 2189 in connect
[2m[33m(raylet, ip=10.120.204.4)[0m   File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/workers/default_worker.py", line 234 in <module>
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m Traceback (most recent call last):
[2m[33m(raylet, ip=10.120.204.4)[0m   File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/workers/default_worker.py", line 246, in <module>
[2m[33m(raylet, ip=10.120.204.4)[0m     out_file, err_file = node.get_log_file_handles(
[2m[33m(raylet, ip=10.120.204.4)[0m   File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/node.py", line 724, in get_log_file_handles
[2m[33m(raylet, ip=10.120.204.4)[0m     log_stdout = open_log(self._get_log_file_name(name, "out", unique=unique))
[2m[33m(raylet, ip=10.120.204.4)[0m   File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/utils.py", line 465, in open_log
[2m[33m(raylet, ip=10.120.204.4)[0m     stream = open(path, **kwargs)
[2m[33m(raylet, ip=10.120.204.4)[0m OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/logs/worker-2a12f113076330785d560af40bf059fc2414997b97285fdc57aad2bc-67000000-3692697.out'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:02:12,688 E 3692697 3692697] logging.cc:104: Stack trace: 
[2m[33m(raylet, ip=10.120.204.4)[0m  /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_raylet.so(+0xd6f36a) [0x14e52358536a] ray::operator<<()
[2m[33m(raylet, ip=10.120.204.4)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_raylet.so(+0xd71b28) [0x14e523587b28] ray::TerminateHandler()
[2m[33m(raylet, ip=10.120.204.4)[0m /mnt/netapp1/Optcesga_FT2_RHEL7/2022/gentoo/31032022/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6(+0xa8a76) [0x14e5226a6a76]
[2m[33m(raylet, ip=10.120.204.4)[0m /mnt/netapp1/Optcesga_FT2_RHEL7/2022/gentoo/31032022/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6(+0xa8ae1) [0x14e5226a6ae1]
[2m[33m(raylet, ip=10.120.204.4)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_raylet.so(+0x6c24b9) [0x14e522ed84b9]
[2m[33m(raylet, ip=10.120.204.4)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_raylet.so(_ZN3ray4core6worker19TaskEventBufferImplD0Ev+0x12) [0x14e522ed84d2] ray::core::worker::TaskEventBufferImpl::~TaskEventBufferImpl()
[2m[33m(raylet, ip=10.120.204.4)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_raylet.so(_ZN3ray4core10CoreWorkerD1Ev+0x50) [0x14e522e55c80] ray::core::CoreWorker::~CoreWorker()
[2m[33m(raylet, ip=10.120.204.4)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_raylet.so(+0x53ea6a) [0x14e522d54a6a] std::_Sp_counted_base<>::_M_release()
[2m[33m(raylet, ip=10.120.204.4)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_raylet.so(_ZN3ray4core21CoreWorkerProcessImplD1Ev+0x1
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/1f3af424ffc94c9494a9b0c04c2bca20-multi-46'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/1f3af424ffc94c9494a9b0c04c2bca20-multi-46'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/dcf52b87f8a74dcaa05c8649dca4dbea-multi-48'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/dcf52b87f8a74dcaa05c8649dca4dbea-multi-48'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/50f47dd3c10d4ccb9bee3f16d103bb69-multi-48'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/50f47dd3c10d4ccb9bee3f16d103bb69-multi-48'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/e4f04f0f16524c048ab43dda31a14d0b-multi-49'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/e4f04f0f16524c048ab43dda31a14d0b-multi-49'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/fe5d87bbe6a54f0e9b0e7cc38261ab19-multi-63'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/fe5d87bbe6a54f0e9b0e7cc38261ab19-multi-63'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/fdfb6a837e544dfdb2d4ac4a0aae29a0-multi-71'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/fdfb6a837e544dfdb2d4ac4a0aae29a0-multi-71'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/252ffef11bbe4e7f8ee3af81f4098b42-multi-75'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/252ffef11bbe4e7f8ee3af81f4098b42-multi-75'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/bc6cac41b1ad4bb69ab8427d6248d2c7-multi-76'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/bc6cac41b1ad4bb69ab8427d6248d2c7-multi-76'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/4f4d268238894fbebdefd6b1715d85cc-multi-1'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/4f4d268238894fbebdefd6b1715d85cc-multi-1'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:04:12,643 E 3645889 3645889] (raylet) worker_pool.cc:537: Some workers of the worker process(3692899) have not registered within the timeout. The process is dead, probably it crashed during start.
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:04:13,491 E 3645889 3645889] (raylet) worker_pool.cc:537: Some workers of the worker process(3692902) have not registered within the timeout. The process is dead, probably it crashed during start.
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:05:26,205 E 3645889 3646047] (raylet) file_system_monitor.cc:111: /scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500 is over 99.9% full, available space: 816300032; capacity: 837278007296. Object creation will fail if spilling is required.
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m terminate called after throwing an instance of 'spdlog::spdlog_ex'
[2m[33m(raylet, ip=10.120.204.4)[0m   what():  Failed opening file /scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/logs/python-core-worker-aefb286fb9413cd64c568529f19382b9d2cfc18ebb65e1db66b9d342_3696561.log for writing: No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m Fatal Python error: Aborted
[2m[33m(raylet, ip=10.120.204.4)[0m 
[2m[33m(raylet, ip=10.120.204.4)[0m Stack (most recent call first):
[2m[33m(raylet, ip=10.120.204.4)[0m   File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/worker.py", line 2189 in connect
[2m[33m(raylet, ip=10.120.204.4)[0m   File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/workers/default_worker.py", line 234 in <module>
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:05:36,238 E 3645889 3646047] (raylet) file_system_monitor.cc:111: /scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500 is over 99.9% full, available space: 0; capacity: 837278007296. Object creation will fail if spilling is required.
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m terminate called after throwing an instance of 'spdlog::spdlog_ex'
[2m[33m(raylet, ip=10.120.204.4)[0m   what():  Failed opening file /scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/logs/python-core-worker-4e2655893c41cf750c8528a286d8ca91e0f166c0697d7c6a4ebfaf84_3696665.log for writing: No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m Fatal Python error: Aborted
[2m[33m(raylet, ip=10.120.204.4)[0m 
[2m[33m(raylet, ip=10.120.204.4)[0m Stack (most recent call first):
[2m[33m(raylet, ip=10.120.204.4)[0m   File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/worker.py", line 2189 in connect
[2m[33m(raylet, ip=10.120.204.4)[0m   File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/workers/default_worker.py", line 234 in <module>
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/d23db47c1acc41b797fb06c46979021c-multi-76'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/d23db47c1acc41b797fb06c46979021c-multi-76'
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:05:46,241 E 3645889 3646047] (raylet) file_system_monitor.cc:111: /scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500 is over 99.9% full, available space: 0; capacity: 837278007296. Object creation will fail if spilling is required.
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:05:56,243 E 3645889 3646047] (raylet) file_system_monitor.cc:111: /scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500 is over 99.9% full, available space: 0; capacity: 837278007296. Object creation will fail if spilling is required.
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/9dd3adadc890432dad1007afd164dd4e-multi-1'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/9dd3adadc890432dad1007afd164dd4e-multi-1'
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:06:06,245 E 3645889 3646047] (raylet) file_system_monitor.cc:111: /scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500 is over 99.9% full, available space: 0; capacity: 837278007296. Object creation will fail if spilling is required.
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/fd8e166750064fb8a90b4a0ab48b86b1-multi-82'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/fd8e166750064fb8a90b4a0ab48b86b1-multi-82'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 304, in spill_objects
    with open(url, "wb", buffering=self._buffer_size) as f:
OSError: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/c4b064680b0b4b60b3c44e8f524837d6-multi-82'
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device: '/scratch/10942690/ray/session_2025-03-12_18-47-23_295008_3034500/ray_spilled_objects/c4b064680b0b4b60b3c44e8f524837d6-multi-82'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1311, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 1314, in ray._raylet.spill_objects_handler
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 668, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 305, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/external_storage.py", line 149, in _write_multiple_objects
    written_bytes = f.write(payload)
OSError: [Errno 28] No space left on device
An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:06:33,629 E 3645889 3645889] (raylet) worker_pool.cc:537: Some workers of the worker process(3696561) have not registered within the timeout. The process is dead, probably it crashed during start.
[2m[33m(raylet, ip=10.120.204.4)[0m [2025-03-12 19:06:37,590 E 3645889 3645889] (raylet) worker_pool.cc:537: Some workers of the worker process(3696665) have not registered within the timeout. The process is dead, probably it crashed during start.
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 10942690 ON ilk-145 CANCELLED AT 2025-03-12T19:07:30 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 10942690.8 ON ilk-146 CANCELLED AT 2025-03-12T19:07:30 DUE TO TIME LIMIT ***
